// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: vector/vector.proto

package vector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectorMemoryService_GetContext_FullMethodName = "/vector.VectorMemoryService/GetContext"
)

// VectorMemoryServiceClient is the client API for VectorMemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorMemoryServiceClient interface {
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error)
}

type vectorMemoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorMemoryServiceClient(cc grpc.ClientConnInterface) VectorMemoryServiceClient {
	return &vectorMemoryServiceClient{cc}
}

func (c *vectorMemoryServiceClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextResponse)
	err := c.cc.Invoke(ctx, VectorMemoryService_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorMemoryServiceServer is the server API for VectorMemoryService service.
// All implementations must embed UnimplementedVectorMemoryServiceServer
// for forward compatibility.
type VectorMemoryServiceServer interface {
	GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error)
	mustEmbedUnimplementedVectorMemoryServiceServer()
}

// UnimplementedVectorMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorMemoryServiceServer struct{}

func (UnimplementedVectorMemoryServiceServer) GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedVectorMemoryServiceServer) mustEmbedUnimplementedVectorMemoryServiceServer() {}
func (UnimplementedVectorMemoryServiceServer) testEmbeddedByValue()                             {}

// UnsafeVectorMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorMemoryServiceServer will
// result in compilation errors.
type UnsafeVectorMemoryServiceServer interface {
	mustEmbedUnimplementedVectorMemoryServiceServer()
}

func RegisterVectorMemoryServiceServer(s grpc.ServiceRegistrar, srv VectorMemoryServiceServer) {
	// If the following call panics, it indicates UnimplementedVectorMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorMemoryService_ServiceDesc, srv)
}

func _VectorMemoryService_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorMemoryServiceServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorMemoryService_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorMemoryServiceServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorMemoryService_ServiceDesc is the grpc.ServiceDesc for VectorMemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorMemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vector.VectorMemoryService",
	HandlerType: (*VectorMemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContext",
			Handler:    _VectorMemoryService_GetContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vector/vector.proto",
}
