// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: vector/vector.proto

package vector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_vector_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_vector_vector_proto_rawDescGZIP(), []int{0}
}

func (x *GetContextRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetContextRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ContextItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_vector_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_vector_vector_proto_rawDescGZIP(), []int{1}
}

func (x *GetContextResponse) GetItems() []*ContextItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetContextResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ContextItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	RelevanceScore float64                `protobuf:"fixed64,3,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	Timestamp      int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContextItem) Reset() {
	*x = ContextItem{}
	mi := &file_vector_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextItem) ProtoMessage() {}

func (x *ContextItem) ProtoReflect() protoreflect.Message {
	mi := &file_vector_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextItem.ProtoReflect.Descriptor instead.
func (*ContextItem) Descriptor() ([]byte, []int) {
	return file_vector_vector_proto_rawDescGZIP(), []int{2}
}

func (x *ContextItem) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ContextItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContextItem) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *ContextItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_vector_vector_proto protoreflect.FileDescriptor

const file_vector_vector_proto_rawDesc = "" +
	"\n" +
	"\x13vector/vector.proto\x12\x06vector\"B\n" +
	"\x11GetContextRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"`\n" +
	"\x12GetContextResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.vector.ContextItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x8d\x01\n" +
	"\vContextItem\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12'\n" +
	"\x0frelevance_score\x18\x03 \x01(\x01R\x0erelevanceScore\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2Z\n" +
	"\x13VectorMemoryService\x12C\n" +
	"\n" +
	"GetContext\x12\x19.vector.GetContextRequest\x1a\x1a.vector.GetContextResponseB9Z7github.com/vwency/resilient-scatter-gather/proto/vectorb\x06proto3"

var (
	file_vector_vector_proto_rawDescOnce sync.Once
	file_vector_vector_proto_rawDescData []byte
)

func file_vector_vector_proto_rawDescGZIP() []byte {
	file_vector_vector_proto_rawDescOnce.Do(func() {
		file_vector_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_vector_proto_rawDesc), len(file_vector_vector_proto_rawDesc)))
	})
	return file_vector_vector_proto_rawDescData
}

var file_vector_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vector_vector_proto_goTypes = []any{
	(*GetContextRequest)(nil),  // 0: vector.GetContextRequest
	(*GetContextResponse)(nil), // 1: vector.GetContextResponse
	(*ContextItem)(nil),        // 2: vector.ContextItem
}
var file_vector_vector_proto_depIdxs = []int32{
	2, // 0: vector.GetContextResponse.items:type_name -> vector.ContextItem
	0, // 1: vector.VectorMemoryService.GetContext:input_type -> vector.GetContextRequest
	1, // 2: vector.VectorMemoryService.GetContext:output_type -> vector.GetContextResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vector_vector_proto_init() }
func file_vector_vector_proto_init() {
	if File_vector_vector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_vector_proto_rawDesc), len(file_vector_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_vector_proto_goTypes,
		DependencyIndexes: file_vector_vector_proto_depIdxs,
		MessageInfos:      file_vector_vector_proto_msgTypes,
	}.Build()
	File_vector_vector_proto = out.File
	file_vector_vector_proto_goTypes = nil
	file_vector_vector_proto_depIdxs = nil
}
