// Code generated by mockery v2.53.5. DO NOT EDIT.

package handler_test

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vector "github.com/vwency/resilient-scatter-gather/proto/vector"
)

// VectorMemoryServiceClient is an autogenerated mock type for the VectorMemoryServiceClient type
type VectorMemoryServiceClient struct {
	mock.Mock
}

// GetContext provides a mock function with given fields: ctx, chatID
func (_m *VectorMemoryServiceClient) GetContext(ctx context.Context, chatID string) (*vector.GetContextResponse, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 *vector.GetContextResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*vector.GetContextResponse, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *vector.GetContextResponse); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vector.GetContextResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVectorMemoryServiceClient creates a new instance of VectorMemoryServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVectorMemoryServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *VectorMemoryServiceClient {
	mock := &VectorMemoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
