// Code generated by mockery v2.53.5. DO NOT EDIT.

package handler_test

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	permissions "github.com/vwency/resilient-scatter-gather/proto/permissions"
)

// PermissionsService is an autogenerated mock type for the PermissionsService type
type PermissionsService struct {
	mock.Mock
}

// CheckAccess provides a mock function with given fields: ctx, userID, resourceID
func (_m *PermissionsService) CheckAccess(ctx context.Context, userID string, resourceID string) (*permissions.CheckAccessResponse, error) {
	ret := _m.Called(ctx, userID, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for CheckAccess")
	}

	var r0 *permissions.CheckAccessResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*permissions.CheckAccessResponse, error)); ok {
		return rf(ctx, userID, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *permissions.CheckAccessResponse); ok {
		r0 = rf(ctx, userID, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permissions.CheckAccessResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPermissionsService creates a new instance of PermissionsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionsService {
	mock := &PermissionsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
